import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const LINKEDIN = 'https://www.linkedin.com/in/brian-sung-bb08ba106/'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>seoulection</h1>
        <section>
          <Link href="/about">about</Link>
          <a href={LINKEDIN} rel="noopener noreferrer" target="_blank">linkedin</a>
        </section>
        <section>
          <Link href="/posts/hello-world">hello world</Link>
        </section>
      </main>
    </>
  )
}
