import Head from 'next/head'
import Link from 'next/link'
import About from '../components/About'

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>seoulection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>seoulection</h1>
        <About />
        <section>
          <Link href="/posts/react-page">react page</Link>
          <Link href="/posts/hello-world">hello world</Link>
        </section>
      </main>
    </>
  )
}
