import Head from 'next/head'
import Link from 'next/link'
import About from 'components/About'
import { getSortedPostsData } from 'lib/posts'

interface Home {
  postData: Data[]
}

type Data = {
  id: string
  date: string
  title: string
}

export default function Home({ postData }: Home): JSX.Element {
  return (
    <>
      <Head>
        <title>seoulection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>seoulection</h1>
        <About />
        <section>
          {postData.map(({ id, date, title }: Data) => (
            <Link key={id} href={`/posts/${id}`}>{date} - {title}</Link>
          ))}
        </section>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const postData = await getSortedPostsData()

  return {
    props: {
      postData
    }
  }
}
